# Generated by Django 4.2.11 on 2025-11-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (optional, max 2MB, JPG/PNG only)', null=True, upload_to='profile_photos/%Y/%m/'),
        ),
    ]
