# Generated by Django 4.2.11 on 2025-10-25 19:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now, help_text='Date for which this report is submitted')),
                ('tasks_completed', models.TextField(help_text='List of tasks/activities completed today')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Total hours worked today', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('blockers_issues', models.TextField(blank=True, help_text='Any blockers or issues encountered', null=True)),
                ('next_day_plan', models.TextField(help_text='Plan for tomorrow')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EOD Report',
                'verbose_name_plural': 'EOD Reports',
                'ordering': ['-report_date', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Manager feedback and comments', null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reports.eodreport')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Review',
                'verbose_name_plural': 'Report Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eodreport',
            index=models.Index(fields=['-report_date'], name='reports_eod_report__496980_idx'),
        ),
        migrations.AddIndex(
            model_name='eodreport',
            index=models.Index(fields=['employee', '-report_date'], name='reports_eod_employe_0d8a37_idx'),
        ),
        migrations.AddIndex(
            model_name='eodreport',
            index=models.Index(fields=['status'], name='reports_eod_status_2e2abd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eodreport',
            unique_together={('employee', 'report_date')},
        ),
    ]
