# Generated by Django 4.2.11 on 2025-10-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eodreport',
            name='project_name',
            field=models.CharField(default='Trainee', help_text='Project or task name you worked on', max_length=200),
        ),
    ]
