# Generated by Django 4.2.11 on 2025-11-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_eodreport_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eodreport',
            name='resubmission_count',
            field=models.IntegerField(default=0, help_text='Number of times this report has been resubmitted after rejection (max 3)'),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='review_number',
            field=models.IntegerField(default=1, help_text='Review iteration number (1st review, 2nd review, etc.)'),
        ),
        migrations.AlterField(
            model_name='reportreview',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reports.eodreport'),
        ),
        migrations.AlterField(
            model_name='reportreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportreview',
            unique_together={('report', 'review_number')},
        ),
    ]
